---
language: groovy
jdk:
  - oraclejdk7
  - oraclejdk8

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.rvm/
    - $HOME/.m2/
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/dependencies/
    - build/gradleDist/
before_install:
  - .travis/install_current_mirah

