#!/bin/bash
#

function install_rvm() {
	if ! which rvm; then
		gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
		
		# Download the installer
		\curl -O https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer
		\curl -O https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer.asc
		
		# Verify the installer signature (might need `gpg2`), and if it validates...
		gpg --verify rvm-installer.asc &&
		
		# Run the installer
		bash rvm-installer stable
	fi
}

function install_jruby() {
	install_rvm
	which jruby || rvm install jruby-9.0.5.0
}


function install_mirah() {
	install_jruby
	
	MIRAH_DIR="$HOME/dependencies/felixvf/mirah"
	
	git clone --depth=100 --branch=master https://github.com/felixvf/mirah.git "$MIRAH_DIR"
	cd "$MIRAH_DIR"
	source ~/.rvm/scripts/rvm
	rvm use jruby-9.0.5.0
	mvn install
}

install_mirah

